[package]
name = "lbx"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
liblbx = { path = "../liblbx" }

dirs = "5.0.1"
crossterm = { version = "0.27.0", features = ["events"] }
arboard = "3.2.1"
